//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llegada
    {
        public int idParada { get; set; }
        public int idViaje { get; set; }
        public System.TimeSpan hora { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Parada Parada { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
