//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasaje
    {
        public int IdPasaje { get; set; }
        public Nullable<int> Asientos { get; set; }
        public string Documento { get; set; }
        public string TipoDocuemtno { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public int IdViaje { get; set; }
        public int IdParadaDestino { get; set; }
        public int IdParadaOrigen { get; set; }
    
        public virtual Parada Parada { get; set; }
        public virtual Parada Parada1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
