//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int IdPrecio { get; set; }
        public int Precio1 { get; set; }
        public System.DateTime FechaEntradaVigencia { get; set; }
        public int IdLinea { get; set; }
        public int IdParada { get; set; }
    
        public virtual Tramo Tramo { get; set; }
    }
}
