//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tramo()
        {
            this.Precio = new HashSet<Precio>();
        }
    
        public int IdLinea { get; set; }
        public int IdParada { get; set; }
        public int TiempoEstimado { get; set; }
        public int Orden { get; set; }
    
        public virtual Linea Linea { get; set; }
        public virtual Parada Parada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precio { get; set; }
    }
}
